/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/STujSpGrn3H
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

import { Search, CirclePlus, FlaskConical, Heart } from "lucide-react"

const specs = [
  {
    name: "Margarita",
    numIngredients: 5,
    numLikes: 120
  },
  {
    name: "Old Fashioned",
    numIngredients: 3,
    numLikes: 80
  },
  {
    name: "Negroni",
    numIngredients: 3,
    numLikes: 90
  },
  {
    name: "Manhattan",
    numIngredients: 3,
    numLikes: 75
  }
];

const specsFromFriends = [
  {
    name: "Mojito",
    numIngredients: 6,
    numLikes: 110
  },
  {
    name: "Cosmopolitan",
    numIngredients: 4,
    numLikes: 25
  },
  {
    name: "Daiquiri",
    numIngredients: 3,
    numLikes: 100
  },
  {
    name: "French 75",
    numIngredients: 3,
    numLikes: 75
  }
];

export function Specs() {
  return (
    <div className="flex flex-col min-h-screen bg-background text-foreground">
      <header className="sticky top-0 z-20 bg-background border-b">
        <div className="container flex items-center justify-between py-4 px-4 md:px-6">
          <h1 className="text-2xl font-bold">Specs</h1>
          <div className="relative flex-1 max-w-md">
            <div className="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
              <Search className="w-5 h-5 text-muted-foreground" />
            </div>
            <Input
              type="search"
              placeholder="Search specs..."
              className="w-full pl-10 pr-4 py-2 rounded-md bg-muted text-foreground focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent"
            />
          </div>
          <Button
            variant="outline"
            size="icon"
            className="ml-4 rounded-full bg-primary text-primary-foreground hover:bg-primary/80 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
          >
            <CirclePlus className="w-6 h-6" />
            <span className="sr-only">Add Spec</span>
          </Button>
        </div>
      </header>

      <main className="flex-1 container py-8 px-4 md:px-6">

        <h2 className="text-xl font-bold mb-4">My Specs</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
          {specs.map(spec => (
            <div className="group">
              <div className="relative overflow-hidden rounded-lg shadow-lg">
                <img
                  src="/placeholder.svg"
                  alt={spec.name}
                  width={400}
                  height={400}
                  className="w-full h-48 object-cover group-hover:opacity-80 transition-opacity"
                />
                <div className="absolute inset-0 flex items-center justify-center bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity">
                  <h3 className="text-white text-lg font-bold">{spec.name}</h3>
                </div>
                <div className="p-2 bg-muted rounded-b-lg">
                  <div className="flex justify-between items-center">
                    <div className="text-sm font-medium">{spec.name}</div>
                    <div className="flex items-center gap-1 text-sm">
                      <FlaskConical className="w-4 h-4" />
                      <span>{spec.numIngredients}</span>
                      <Heart className="w-4 h-4" />
                      <span>{spec.numLikes}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
        
        <h2 className="text-xl font-bold mb-4 mt-8">Specs Added by Friends</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
          {specsFromFriends.map(spec => (
            <div className="group">
              <div className="relative overflow-hidden rounded-lg shadow-lg">
                <img
                  src="/placeholder.svg"
                  alt={spec.name}
                  width={400}
                  height={400}
                  className="w-full h-48 object-cover group-hover:opacity-80 transition-opacity"
                />
                <div className="absolute inset-0 flex items-center justify-center bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity">
                  <h3 className="text-white text-lg font-bold">{spec.name}</h3>
                </div>
                <div className="p-2 bg-muted rounded-b-lg">
                  <div className="flex justify-between items-center">
                    <div className="text-sm font-medium">{spec.name}</div>
                    <div className="flex items-center gap-1 text-sm">
                      <FlaskConical className="w-4 h-4" />
                      <span>{spec.numIngredients}</span>
                      <Heart className="w-4 h-4" />
                      <span>{spec.numLikes}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

      </main>
    </div>
  )
}
